### ISSUE TITLE
$response->getEffectiveUrl() doesn't return correct url after redirects

### ISSUE THREAD

**Issue by DangerLifter** [WyriHaximus/ReactGuzzleRing#11]
According to guzzle docs:
Effective URL: The URL that was ultimately accessed that returned a response can be accessed using the getEffectiveUrl() method of a response. This method will return the URL of a request or the URL of the last redirected URL if any redirects occurred while transferring a request.

And it is really works this way. Wiht handler first requested url is returned. Test page: http://eigenoverzicht.nl/
Handler returns: http://eigenoverzicht.nl/
Guzzle returns: http://www.eigenstart.nl/?ref=

**Comment by WyriHaximus** [comment]
Thanks once again for reporting this :+1: . Been looking into it and somewhere between the handler and Guzzle it goes wrong. I can see it beeing handed over with the correct URL (the 3rd) but for some reason it won't show up in the end.

**Comment by WyriHaximus** [comment]
Hah found the 'source' of the issue! No fix yet but found the origin of where it goes wrong.

**Comment by WyriHaximus** [comment]
Fixed it with 0a4c0d8 by removing redirection handling which is done by Guzzle :smile: .
