### ISSUE TITLE
After last update with "redirect" I got bunch of redirect issues:

### ISSUE THREAD

**Issue by DangerLifter** [WyriHaximus/ReactGuzzleRing#12]
http://www.eltiempo.com/enviar_contenido/getligthbox/ec_reportar_error/82497 - " does not use one of the allowed redirect protocols: http, https".

And tons of "Will not follow more than XX redirects". Eg. "http://www.rockpapershotgun.com/forums/showthread.php?10115-What-good-PC-games-have-local-co-op=&10115-What-good-PC-games-have-local-co-op%2Fpage2=&p=313333&viewfull=1". Dumping new location points that it tries redirect to same url each time.

Before I had nothing similar.

**Comment by DangerLifter** [comment]
Ok. Seems I know Why I didn't see similar issues before - because I proceed "execeeds maximum redirects error" from handler. And now my try-catch should catch exception from guzzle.
But I wonder Is provided urls are really unresolved in terms of redirect?

**Comment by WyriHaximus** [comment]
Yeah correct, the later is a guzzle safeguard from hammering servers with redirect loops. You can specify how many redirects to follow: http://guzzle.readthedocs.org/en/latest/clients.html#allow-redirects

The former is more interesting. I'm going to propose a PR to Guzzle to fix that. The previous link shows that the default is `http` or `https`. The check that causes the error is done case sensitive.

**Comment by WyriHaximus** [comment]
Neat, the PR is merged, that should solve the uppercase scheme issue :+1: . if the other issue isn't an issue anymore, can you close this issue?

**Comment by DangerLifter** [comment]
Thanks for quick response as usually.
Concerning redirect issue, example url correctly works with browser and WGET. Eg. firefox debug console shows "200 Ok" response for this url instead of redirect. Probably it is some issue with client code.

**Comment by WyriHaximus** [comment]
Great to hear! If you increase the max redirect limit it should work out I suppose :+1: .
