### ISSUE TITLE
Redirect doesn't work

### ISSUE THREAD

**Issue by DangerLifter** [WyriHaximus/ReactGuzzleRing#3]
Currently requests with redirect doesn't work and thro exception "Waiting did not resolve future". Can be tested on "examples/redirec.php" as-is oon fresh installation.

**Comment by DangerLifter** [comment]
Works for me. thx.

**Comment by WyriHaximus** [comment]
Awesome, thanks for letting me know :+1: .

**Comment by DangerLifter** [comment]
Redirect doesn't work for some sites. eg: http://website.com/robots.txt

**Comment by WyriHaximus** [comment]
Interesting I'll have a look at it

**Comment by DangerLifter** [comment]
Just debugged a bit. Issue is about not updated $request['headers']['host'] value when follow redirects. New request in method "followRedirect" used old $this->request array which contains old  "Host" header value inside. 
See also \GuzzleHttp\Message::updateHostHeaderFromUrl();
Not sure How to fix it right way. Just made simple "Host" update  (right before new request in "followRedirect") and it works for me in this particular case.

**Comment by WyriHaximus** [comment]
I'll have a look at it and aim to finish it before dinner (which is in 3 hours). Thanks for digging into this, this explains why the HTTP to HTTPS redirect on github works fine.

P.S. thanks for making me feel like this :+1: :
![Doh!](http://rafinhaea7arte.files.wordpress.com/2010/04/homer-doh.gif)

**Comment by WyriHaximus** [comment]
Have a working fix locally, working on rechecken everything and adjusting where needed since I've also got #2 in at the same time.

**Comment by WyriHaximus** [comment]
2c73dae should fix it @DangerLifter, can you confirm?

**Comment by DangerLifter** [comment]
Redirect works. But now on success response: (string) $reponse->getBody() causes:

PHP Catchable fatal error:  Argument 1 passed to GuzzleHttp\Stream\Utils::copyToString() must implement interface GuzzleHttp\Stream\StreamInterface, null given, called in /var/www/projects/DomainScrapper/vendor/wyrihaximus/react-guzzle-ring/src/HttpClient/Stream.php on line 119 and defined in /var/www/projects/DomainScrapper/vendor/guzzlehttp/streams/src/Utils.php on line 56
PHP Stack trace:

**Comment by WyriHaximus** [comment]
Will look at it, in the mean time `$response->getBody()->getContents()` will do the same.

**Comment by DangerLifter** [comment]
Thx. I've already used this way.

**Comment by WyriHaximus** [comment]
Cheers, already located the issue, will fix it during lunch break :+1: . Going to come up with a way to test all these things in the test suite in the future.

**Comment by WyriHaximus** [comment]
Fix is up :).

**Comment by DangerLifter** [comment]
Not sure who is responsible for this bug but: 
url: http://www.whatsoncornwall.co.uk/rss
If I use clean Guzzle - it works.
If I use React RIng adapter - than I got "DNS Request did not return valid answer.". It doesn' matter do I use "8.8.8.8" dns  or leave it as null for handler.

**Comment by WyriHaximus** [comment]
Just tested it locally and it works fine for me. Have you tried you local networks DNS server or your ISP's DNS server?

**Comment by DangerLifter** [comment]
Hey. I just dig it again. Not sure why you can't produce problem. Try another url "'http://www.falriver.co.uk/whats-on/fal-river-festival-18381'"
But here it is some explanation of issue. 
Take a look at : GuzzleHttp\Subscriber::modifyRedirectRequest line 120 It calls GuzzleHttp\Subscriber::setRedirectUrl which set proper url for redirect. In failed cases location contains not absolute url (in above url new location si just "/whats-on/fal-river-festival"). So guzzle correctly update relative url in method GuzzleHttp\Subscriber::setRedirectUrl().
In react ring "relative location" jsut set as new url. So it doesn't contain host part. And query to DNS goes with empty host value. Which causes above problem.

**Comment by WyriHaximus** [comment]
Pushed a commit that utilizes the Url class from Guzzle to combine the location header into the old URL and get the correct URL after the redirect from it. Thanks again for pointing out a flaw, I really appreciate it. 

Also I'm really interested in how you use this package. If you like to share can you send me an email to the email address on my profile page?

**Comment by DangerLifter** [comment]
Thanks, works for me on simple tests. Will let you know if I catch any issues in more complex cases.
Can't share with you any details, because of agreement. Just say it is used for internet crawler project.
Thanks for quick response.

**Comment by WyriHaximus** [comment]
Cheers, let me know if you run into any issues later on. No worries I completely understand :smile: . Thanks for using my project and giving feedback :+1: !
