### ISSUE TITLE
Timeout and not full content

### ISSUE THREAD

**Issue by DangerLifter** [WyriHaximus/ReactGuzzleRing#5]
I am not sure about this issue in terms is it problem of handler or guzzle itself.
If donwloaded large file on timeout I don't catch any errors but get only part of response content.

**Comment by WyriHaximus** [comment]
Let me know if that helped and reopen it if it doesn't. Also raise the request time out (the `timeout` setting) so it doesn't times out. It's correct that you won't get full contents if the request times out but it should have rejected the promise.
