### ISSUE TITLE
Fatal: Unable to parse malformed url: http://

### ISSUE THREAD

**Issue by DangerLifter** [WyriHaximus/ReactGuzzleRing#6]
Problems come again from redirect. Test url: "https://hover.com/alerts/alert_bulletin/22/click". After few redirects Guzzle are redirected to "http://". Without handler works "ok".

**Comment by DangerLifter** [comment]
Hi, Sorry for bothering as usually, But any chance to get this fixed today?

**Comment by WyriHaximus** [comment]
Interesting bug, the server returns http:// as location, digging into guzzles internals on how to solve this.
